apiVersion: apps/v1
kind: Deployment
metadata:
  name: webprofile-session-deployment
  labels:
    app: webprofile-session
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webprofile-session
  template:
    metadata:
      labels:
        app: webprofile-session
    spec:
      containers:
      - name: webprofile-session-container
        image: webprofile-session:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: webprofile-session-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webprofile-session
  ports:
  - port: 80
    targetPort: 9080